apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
  name: onestop-frontend-ingress
  namespace: onestop
spec:
  ingressClassName: nginx
  rules:
    - host: onestop.host
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: onestop-frontend
                port:
                  number: 51200